version: '3.8'

services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - whatsapp_bot_network

networks:
  whatsapp_bot_network:
    external: false