name: publish

on:
  push:
    branches: ["main"]

jobs:
  create-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_CD }}
        
      - name: Build the Docker image
        run: |
          docker build --tag ${{ secrets.DOCKER_PRODUCTION_IMAGE }} .
          docker push ${{ secrets.DOCKER_PRODUCTION_IMAGE }} 

  deploy:
    needs: create-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: Remote SSH deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.PROJECT_DIR }}
            docker login ghcr.io -u mhp24 -p ${{ secrets.TOKEN_CD }}
            docker compose -f docker-compose.prod.yml down
            docker container prune -f
            docker image rm ${{ secrets.DOCKER_PRODUCTION_IMAGE }} -f 
            docker compose -f docker-compose.prod.yml up -d
